import budget_router


def test_public_api_preserves_supported_imports() -> None:
    assert budget_router.__all__ == [
        "ActionEstimate",
        "AgentPrefixSummary",
        "AgentStepDecision",
        "Budget",
        "BudgetExceededError",
        "BudgetLedger",
        "DiffSummary",
        "EventKind",
        "FactorizedRouterPolicy",
        "FrozenAgentStepArtifact",
        "FrozenAgentStepRouter",
        "GoalContext",
        "GuardedAgentStepArtifact",
        "GuardedAgentStepRouter",
        "HashedLinearModelHead",
        "ModelPrice",
        "ModelCard",
        "Operation",
        "PriceSnapshot",
        "ReasonCode",
        "RouterAction",
        "RouterConfig",
        "RouterDecision",
        "RouterEvent",
        "RouterSession",
        "RouterState",
        "TerminalOutcome",
        "SemanticOutcome",
        "SemanticEvaluationOutcome",
        "SemanticAgentRouteDecision",
        "SemanticAgentRouter",
        "SemanticRouteDecision",
        "SemanticRouter",
        "TokenUsage",
        "TranscriptMessage",
        "approximate_context_tokens",
        "render_agent_prefix",
        "train_semantic_router",
        "evaluate_semantic_router",
    ]
